version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nestjs-postgres-prod
    environment:
      POSTGRES_DB: railway
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: XmCxoESLvTcruVRfKmmvNerGVxwQLxlr
    ports:
      - "5432:5432"
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  nestjs-backend:
    image: ghcr.io/candopandu/mikoszeug:latest
    container_name: nestjs-backend-prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      # Railway-style environment variables (matching Railway PostgreSQL)
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: XmCxoESLvTcruVRfKmmvNerGVxwQLxlr
      PGDATABASE: railway
      POSTGRES_DB: railway
      POSTGRES_PASSWORD: XmCxoESLvTcruVRfKmmvNerGVxwQLxlr
      POSTGRES_USER: postgres
      # Fallback to old-style for compatibility
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: XmCxoESLvTcruVRfKmmvNerGVxwQLxlr
      DB_DATABASE: railway
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

volumes:
  postgres_prod_data:

networks:
  app-network:
    driver: bridge