version: '3.8'

services:
  nestjs-backend:
    image: ghcr.io/candopandu/mikoszeug:latest
    container_name: nestjs-backend-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s